### ISSUE TITLE
Vault doesn't return an empty string if one is set

### ISSUE THREAD

**Issue by wlaurance** [jimmybyrum/vault.js#11]
In my code I am doing the following:

```javascript
Vault.set('hello', '')
```

I'd expect it to return an empty string, but I get this instead:

```javascript
Vault.get('hello')
undefined
```

It seems to be affecting all of the stores.

Any help would be appreciated! Thanks

**Comment by jimmybyrum** [comment]
@wlaurance I updated this to more strictly respect what you put in storage. Empty strings should work as expected now, as should `undefined` and `null` (in case you want to store those explicitly):
```js
Vault.set('hello', '');
Vault.get('hello');
''

Vault.set('hello', null);
Vault.get('hello');
null

Vault.set('hello', undefined);
Vault.get('hello');
undefined
```
